name: Update README with Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub README Google Scholar
        uses: soroushchehresa/github-readme-google-scholar@master
        with:
          scholar_id: SJrkyKIAAAAJ
