name: Update README with Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/ReadmeScholar@main
        with:
          SCHOLAR_ID: SJrkyKIAAAAJ
          MAX_COUNT: 5
          FILE_PATH: README.md
